export enum EventType {
  Destroy = 'destroy',
  Ready = 'ready',
  Unstarted = 'unstarted',
  Ended = 'ended',
  Played = 'played',
  Paused = 'paused',
  Buffering = 'buffering',
  Cued = 'cued',
  VolumeChange = 'volume-change',
  Seeked = 'seeked',
  QualityChange = 'quality-change',
  RateChange = 'rate-change',
  ApiChange = 'api-change',
  SizeChange = 'size-change',
  FullscreenChange = 'fullscreen-change',
  Error = 'error',
  AdUnstarted = 'ad-unstarted',
  AdEnded = 'ad-ended',
  AdPlayed = 'ad-played',
  AdPaused = 'ad-paused',
  AdBuffering = 'ad-buffering',
  AdCued = 'ad-cued',
  /** The share panel on embedded YouTube videos */
  SharePanelOpened = 'share-panel-opened',
  LoadProgress = 'load-progress',
  VideoProgress = 'video-progress',
  ReloadRequired = 'reload-required',
  CueRangeEnter = 'cue-range-enter',
  CueRangeExit = 'cue-range-exit',
  ShareClicked = 'share-clicked',
  ConnectionIssue = 'connection-issue',
  VideoDataChange = 'video-data-change',
  PlaylistUpdate = 'playlist-update'
};