export enum EventType {
  READY = 'ready',
  UNSTARTED = 'unstarted',
  ENDED = 'ended',
  PLAYED = 'played',
  PAUSED = 'paused',
  BUFFERING = 'buffering',
  CUED = 'cued',
  VOLUME_CHANGE = 'volume-change',
  SEEKED = 'seeked',
  QUALITY_CHANGE = 'quality-change',
  RATE_CHANGE = 'rate-change',
  API_CHANGE = 'api-change',
  SIZE_CHANGE = 'size-change',
  FULLSCREEN_CHANGE = 'fullscreen-change',
  ERROR = 'error',
  AD_UNSTARTED = 'ad-unstarted',
  AD_ENDED = 'ad-ended',
  AD_PLAYED = 'ad-played',
  AD_PAUSED = 'ad-paused',
  AD_BUFFERING = 'ad-buffering',
  AD_CUED = 'ad-cued',
  /** The share panel on embedded YouTube videos */
  SHARE_PANEL_OPENED = 'share-panel-opened',
  LOAD_PROGRESS = 'load-progress',
  VIDEO_PROGRESS = 'video-progress',
  RELOAD_REQUIRED = 'reload-required',
  CUE_RANGE_ENTER = 'cue-range-enter',
  CUE_RANGE_EXIT = 'cue-range-exit',
  SHARE_CLICKED = 'share-clicked',
  CONNECTION_ISSUE = 'connection-issue',
  VIDEO_DATA_CHANGE = 'video-data-change',
  PLAYLIST_UPDATE = 'playlist-update'
};